# Generated by Django 5.0.6 on 2024-06-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_fname_profile_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(max_length=20),
        ),
    ]
